In [241]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
from subprocess import check_output
print(check_output(["ls", "../Final_Project/Data"]).decode("utf8"))
# Any results you write to the current directory are saved as output.

from ast import literal_eval
import ast

credits.csv
keywords.csv
links.csv
links_small.csv
movies_Merged_Alldata.csv
movies_Merged_Alldata.csv.gz
movies_metadata.csv
ratings.csv
ratings_small.csv

In [242]:
PATH = "../Final_Project/Data/"

In [243]:
df_credits = pd.read_csv(PATH+"credits.csv")
print("credits: \n ", df_credits.columns)
df_keywords = pd.read_csv(PATH+"keywords.csv")
print("\n keywords: \n", df_keywords.columns)

df_links = pd.read_csv(PATH+"links.csv")
print("\n links: \n", df_links.columns)

credits:
  Index(['cast', 'crew', 'id'], dtype='object')

 keywords:
 Index(['id', 'keywords'], dtype='object')

 links:
 Index(['movieId', 'imdbId', 'tmdbId'], dtype='object')

In [244]:
df = pd.read_csv(PATH+"movies_metadata.csv")
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

# Some columns types are read badly : fix
- ID column should be numeric.
- we can see this using dtype (merge/join also would fail).
- it has no nulls though.
- debug by printing non numeric rows in it:
      - Finally: drop these (few) bad rows

In [245]:
df[["id","imdb_id"]].dtypes

id         object
imdb_id    object
dtype: object

In [246]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [247]:
# Only 3 bad rows!
print (df[pd.to_numeric(df['id'], errors='coerce').isnull()])

                                                   adult  \
19730                                 - Written by Ørnås
29503   Rune Balot goes to a casino connected to the ...
35587   Avalanche Sharks tells the story of a bikini ...

      belongs_to_collection                            budget  \
19730              0.065736  /ff9qCepilowshEtG2GYWwzt2bs4.jpg
29503              1.931659  /zV8bHuSL6WXoD6FWogP9j4x80bL.jpg
35587              2.185485  /zaSf5OG7V8X8gqFvly88zDdRm46.jpg

                                                  genres  \
19730  [{'name': 'Carousel Productions', 'id': 11176}...
29503  [{'name': 'Aniplex', 'id': 2883}, {'name': 'Go...
35587  [{'name': 'Odyssey Media', 'id': 17161}, {'nam...

                                                homepage          id imdb_id  \
19730  [{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...  1997-08-20       0
29503  [{'iso_3166_1': 'US', 'name': 'United States o...  2012-09-29       0
35587           [{'iso_3166_1': 'CA', 'name': 'Canada'}]  2014-01-01       0

      original_language                            original_title  overview  \
19730             104.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
29503              68.0      [{'iso_639_1': 'ja', 'name': '日本語'}]  Released
35587              82.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released

         ...     release_date revenue runtime spoken_languages status  \
19730    ...                1     NaN     NaN              NaN    NaN
29503    ...               12     NaN     NaN              NaN    NaN
35587    ...               22     NaN     NaN              NaN    NaN

       tagline  title video vote_average vote_count
19730      NaN    NaN   NaN          NaN        NaN
29503      NaN    NaN   NaN          NaN        NaN
35587      NaN    NaN   NaN          NaN        NaN

[3 rows x 24 columns]

In [248]:
df.shape

(45466, 24)

In [249]:
# Dropping NA values
df["id"] =pd.to_numeric(df['id'], errors='coerce',downcast="integer")
# df["imdb_id"] =pd.to_numeric(df['imdb_id'], errors='coerce',downcast="integer")
df.dropna(subset=["id"],inplace=True)
df.shape

(45463, 24)

In [250]:
df.dropna(subset=["imdb_id"]).shape

(45446, 24)

In [251]:
# print(df.shape)
print("df_credits",df_credits.shape)

df_credits (45476, 3)

In [252]:
df_credits.head(3)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602

In [253]:
df.head(3)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844.0,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602.0,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0

In [254]:
df = df.merge(df_credits,on=["id"],how="left")

In [255]:
print(df_links.shape)
df_links.head()

(45843, 3)

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [256]:
df = df.merge(df_keywords,on=["id"],how="left")

In [257]:
print("missing imdb ids in main data:",df["imdb_id"].isnull().sum())
print("LINK data missing Imdb ids:",df_links["imdbId"].isnull().sum())
print("LINK data missing Tmdb ids:",df_links["tmdbId"].isnull().sum())
# looks like our coercion lost many rows. We don't really care about imdb IDs so we can ignore frankly..

missing imdb ids in main data: 17
LINK data missing Imdb ids: 0
LINK data missing Tmdb ids: 219

In [258]:
# we see matching is poor for ID-movieId- but do we care? 
df.drop(["imdb_id"],axis=1).merge(df_links,left_on="id",right_on="movieId",how="inner").shape

(7767, 29)

In [259]:
# imdbID match rate: 
df.merge(df_links,left_on="imdb_id",right_on="imdbId",how="inner").shape

(0, 30)

In [260]:
df.shape

(46629, 27)

In [261]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,spoken_languages,status,tagline,title,video,vote_average,vote_count,cast,crew,keywords
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [262]:
df.shape

(46629, 27)

In [263]:
df.drop_duplicates().shape

(45463, 27)

# some data cleaning:
- replace 0 budget with NaNs..
- drop row with missing cast/crew

In [264]:
df.isnull().sum()

adult                        0
belongs_to_collection    42055
budget                       0
genres                       0
homepage                 38620
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   995
popularity                   4
poster_path                399
production_companies         4
production_countries         4
release_date                88
revenue                      4
runtime                    268
spoken_languages             4
status                      86
tagline                  25846
title                        4
video                        4
vote_average                 4
vote_count                   4
cast                         1
crew                         1
keywords                     1
dtype: int64

In [265]:
df.dropna(subset=["cast","crew","keywords","popularity"],inplace=True)
print(df.shape)

(46624, 27)

In [266]:
df['budget'] = pd.to_numeric(df['budget'], errors='coerce')
df['budget'] = df['budget'].replace(0, np.nan)

df['revenue'] = df['revenue'].replace(0, np.nan)

In [267]:
vote_counts = df[df['vote_count'].notnull()]['vote_count'].astype('int')
vote_averages = df[df['vote_average'].notnull()]['vote_average'].astype('int')
C = vote_averages.mean()

m = vote_counts.quantile(0.75)

def weighted_rating(x):
    v = x['vote_count']+1 # added +1 - Dan
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)

df['weighted_rating'] = df.apply(weighted_rating, axis=1)

In [268]:
df['genres'] = df['genres'].fillna('[]').apply(literal_eval).apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [269]:
df['cast'] = df['cast'].apply(literal_eval)
df['crew'] = df['crew'].apply(literal_eval)
df['keywords'] = df['keywords'].apply(literal_eval)
df['cast_size'] = df['cast'].apply(lambda x: len(x))
df['crew_size'] = df['crew'].apply(lambda x: len(x))

In [270]:
def get_director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']
    return np.nan
df['director'] = df['crew'].apply(get_director)

In [271]:

df['cast'] = df['cast'].apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])
df['cast'] = df['cast'].apply(lambda x: x[:3] if len(x) >=3 else x)

df['keywords'] = df['keywords'].apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [272]:
df['production_countries'].head()

0    [{'iso_3166_1': 'US', 'name': 'United States o...
1    [{'iso_3166_1': 'US', 'name': 'United States o...
2    [{'iso_3166_1': 'US', 'name': 'United States o...
3    [{'iso_3166_1': 'US', 'name': 'United States o...
4    [{'iso_3166_1': 'US', 'name': 'United States o...
Name: production_countries, dtype: object

In [273]:
df['production_countries'] = df['production_countries'].fillna('[]').apply(ast.literal_eval)
df['production_countries'] = df['production_countries'].apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [274]:
df['production_countries'].head(2)

0    [United States of America]
1    [United States of America]
Name: production_countries, dtype: object

In [275]:
df['revenue_divide_budget'] = df['revenue'] / df['budget']

In [276]:
df['belongs_to_collection'].head()

0    {'id': 10194, 'name': 'Toy Story Collection', ...
1                                                  NaN
2    {'id': 119050, 'name': 'Grumpy Old Men Collect...
3                                                  NaN
4    {'id': 96871, 'name': 'Father of the Bride Col...
Name: belongs_to_collection, dtype: object

In [277]:
df['belongs_to_collection'] = df['belongs_to_collection'].fillna("[]").apply(ast.literal_eval).apply(lambda x: x['name'] if isinstance(x, dict) else np.nan)

In [278]:
## https://www.kaggle.com/rounakbanik/the-story-of-film
df['spoken_languages'] = df['spoken_languages'].fillna('[]').apply(ast.literal_eval).apply(lambda x: len(x) if isinstance(x, list) else np.nan)

In [279]:
df.head(20)['production_companies'].fillna("[]").apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

0     []
1     []
2     []
3     []
4     []
5     []
6     []
7     []
8     []
9     []
10    []
11    []
12    []
13    []
14    []
15    []
16    []
17    []
18    []
19    []
Name: production_companies, dtype: object

In [280]:
df['production_companies'] = df['production_companies'].apply(ast.literal_eval)
df['production_companies'] = df['production_companies'].fillna("[]").apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [281]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,vote_average,vote_count,cast,crew,keywords,weighted_rating,cast_size,crew_size,director,revenue_divide_budget
0,False,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,7.7,5415.0,"[Tom Hanks, Tim Allen, Don Rickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva...",7.684645,13,106,John Lasseter,12.451801
1,False,NaN,65000000.0,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,6.9,2413.0,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'...",6.876926,26,16,Joe Johnston,4.043035
2,False,Grumpy Old Men Collection,NaN,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,6.5,92.0,"[Walter Matthau, Jack Lemmon, Ann-Margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o...",6.162328,7,4,Howard Deutch,NaN
3,False,NaN,16000000.0,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,6.1,34.0,"[Whitney Houston, Angela Bassett, Loretta Devine]","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin...",5.675590,10,10,Forest Whitaker,5.090760
4,False,Father of the Bride Collection,NaN,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,5.7,173.0,"[Steve Martin, Diane Keaton, Martin Short]","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[baby, midlife crisis, confidence, aging, daug...",5.624595,12,7,Charles Shyer,NaN
5,False,NaN,60000000.0,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,7.7,1886.0,"[Al Pacino, Robert De Niro, Val Kilmer]","[{'credit_id': '52fe4292c3a36847f802916d', 'de...","[robbery, detective, bank, obsession, chase, s...",7.656437,65,71,Michael Mann,3.123947
6,False,NaN,58000000.0,"[Comedy, Romance]",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,6.2,141.0,"[Harrison Ford, Julia Ormond, Greg Kinnear]","[{'credit_id': '52fe44959251416c75039da9', 'de...","[paris, brother brother relationship, chauffeu...",6.014294,57,53,Sydney Pollack,NaN
7,False,NaN,NaN,"[Action, Adventure, Drama, Family]",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",...,5.4,45.0,"[Jonathan Taylor Thomas, Brad Renfro, Rachael ...","[{'credit_id': '52fe46bdc3a36847f810f797', 'de...",[],5.331446,7,4,Peter Hewitt,NaN
8,False,NaN,35000000.0,"[Action, Adventure, Thriller]",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,...,5.5,174.0,"[Jean-Claude Van Damme, Powers Boothe, Dorian ...","[{'credit_id': '52fe44dbc3a36847f80ae0f1', 'de...","[terrorist, hostage, explosive, vice president]",5.457491,6,9,Peter Hyams,1.838576
9,False,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,6.6,1194.0,"[Pierce Brosnan, Sean Bean, Izabella Scorupco]","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...","[cuba, falsely accused, secret identity, compu...",6.562340,20,46,Martin Campbell,6.072311
10,False,NaN,62000000.0,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,6.5,199.0,"[Michael Douglas, Annette Bening, Michael J. Fox]","[{'credit_id': '52fe44dac3a36847f80adfa3', 'de...","[white house, usa president, new love, widower...",6.316734,18,6,Rob Reiner,1.739992
11,False,NaN,NaN,"[Comedy, Horror]",NaN,12110,tt0112896,en,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,...,5.7,210.0,"[Leslie Nielsen, Mel Brooks, Amy Yasbeck]","[{'credit_id': '52fe44b79251416c7503e7fb', 'de...","[dracula, spoof]",5.635982,11,9,Mel Brooks,NaN
12,False,Balto Collection,NaN,"[Family, Animation, Adventure]",NaN,21032,tt0112453,en,Balto,An outcast half-wolf risks his life to prevent...,...,7.1,423.0,"[Kevin Bacon, Bob Hoskins, Bridget Fonda]","[{'credit_id': '593f24b9c3a3680369002371', 'de...","[wolf, dog-sledding race, alaska, dog, goose, ...",6.961825,13,14,Simon Wells,NaN
13,False,NaN,44000000.0,"[History, Drama]",NaN,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,7.1,72.0,"[Anthony Hopkins, Joan Allen, Powers Boothe]","[{'credit_id': '52fe43c59251416c7501d6f3', 'de...","[usa president, presidential election, waterga...",6.508558,34,8,Oliver Stone,0.310949
14,False,NaN,98000000.0,"[Action, Adventure]",NaN,1408,tt0112760,en,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",...,5.7,137.0,"[Geena Davis, Matthew Modine, Frank Langella]","[{'credit_id': '52fe42f4c3a36847f802f69f', 'de...","[exotic island, treasure, map, ship, scalp, pi...",5.608812,31,16,Renny Harlin,0.102218
15,False,NaN,52000000.0,"[Drama, Crime]",NaN,524,tt0112641,en,Casino,The life of the gambling paradise – Las Vegas ...,...,7.8,1343.0,"[Robert De Niro, Sharon Stone, Joe Pesci]","[{'credit_id': '52fe424dc3a36847f80139cd', 'de...","[poker, drug abuse, 1970s, overdose, illegal p...",7.736804,45,10,Martin Scorsese,2.232930
16,False,NaN,16500000.0,"[Drama, Romance]",NaN,4584,tt0114388,en,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",...,7.2,364.0,"[Kate Winslet, Emma Thompson, Hugh Grant]","[{'credit_id': '52fe43cec3a36847f807101f', 'de...","[bowling, based on novel, servant, country lif...",7.032871,17,8,Ang Lee,8.181818
17,False,NaN,4000000.0,"[Crime, Comedy]",NaN,5,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,...,6.5,539.0,"[Tim Roth, Antonio Banderas, Jennifer Beals]","[{'credit_id': '52fe420dc3a36847f800011b', 'de...","[hotel, new year's eve, witch, bet, hotel room...",6.425289,24,88,Allison Anders,1.075000
18,False,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,en,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",...,6.1,1128.0,"[Jim Carrey, Ian McNeice, Simon Callow]","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...","[africa, indigenous, human animal relationship...",6.074820,15,11,Steve Oedekerk,7.079518
19,False,NaN,60000000.0,"[Action, Comedy, Crime]",NaN,11517,tt0113845,en,Money Train,A vengeful New York transit cop decides to ste...,...,5.4,224.0,"[Wesley Snipes, Woody Harrelson, Jennifer Lopez]","[{'credit_id': '52fe44509251416c750305a1', 'de...","[brother brother relationship, subway, new yor...",5.378825,15,44,Joseph Ruben,0.590519
20,False,Chili Palmer Collection,30250000.0,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,en,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,...,6.4,305.0,"[John Travolta, Gene Hackman, Rene Russo]","[{'credit_id': '52fe448dc3a36847f809c729', 'de...","[gambling, miami, based on novel, job, murder,...",6.283870,16,26,Barry Sonnenfeld,3.805012
21,False,NaN,NaN,"[Drama, Thriller]",NaN,1710,tt0112722,en,Copycat,An agoraphobic psychologist and a female detec...,...,6.5,199.0,"[Sigourney Weaver, Holly Hunter, Will Patton]","[{'credit_id': '52fe430ec3a36847f803722d', 'de...","[police brutality, psychology, police operatio...",6.316734,15,21,Jon Amiel,NaN
22,False,NaN,50000000.0,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,en,Assassins,Assassin Robert Rath arrives at a funeral to k...,...,6.0,394.0,"[Sylvester Stallone, Antonio Banderas, Juliann...","[{'credit_id': '52fe451cc3a36847f80bd145', 'de...","[competition, assassination, cia, bank, cat, m...",5.939664,17,71,Richard Donner,0.606061
23,False,NaN,NaN,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,en,Powder,Harassed by classmates who won't accept his sh...,...,6.3,143.0,"[Mary Steenburgen, Sean Patrick Flanery, Lance...","[{'credit_id': '52fe45129251416c7504ab67', 'de...","[dead animal, shot to death, teenage boy, held...",6.097279,5,9,Victor Salva,NaN
24,False,NaN,3600000.0,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",...,7.1,365.0,"[Nicolas Cage, Elisabeth Shue, Julian Sands]","[{'credit_id': '52fe4245c3a36847f80111c3', 'de...","[individual, prostitute, alcohol, casino, love...",6.941789,14,12,Mike Figgis,13.833333
25,False,NaN,NaN,[Drama],NaN,16420,tt0114057,en,Othello,The evil Iago pretends to be friend of Othello...,...,7.0,33.0,"[Laurence Fishburne, Irène Jacob, Kenneth Bran...","[{'credit_id': '5462510ec3a368082d000121', 'de...","[shakespeare, jealousy, friends, moor]",6.119348,9,3,Oliver Parker,NaN
26,False,NaN,12000000.0,"[Comedy, Drama, Family]",NaN,9263,tt0114011,en,Now and Then,Waxing nostalgic about the bittersweet passage...,...,6.6,91.0,"[Christina Ricci, Rosie O'Donnell, Thora Birch]","[{'credit_id': '52fe44dec3a36847f80aed45', 'de...","[1970s, female friendship, coming of age, gyne...",6.232664,16,8,Lesli Linka Glatter,2.283333
27,False,NaN,NaN,"[Drama, Romance]",NaN,17015,tt0114117,en,Persuasion,This film adaptation of Jane Austen's last nov...,...,7.4,36.0,"[Amanda Root, Ciarán Hinds, Susan Fleetwood]","[{'credit_id': '52fe46ff9251416c7508a8b3', 'de...","[captain, napoleonic wars, old flame, admiral]",6.365010,26,22,Roger Michell,NaN
28,False,NaN,18000000.0,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,fr,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,...,7.6,308.0,"[Ron Perlman, Dominique Pinon, Judith Vittet]","[{'credit_id': '52fe428ac3a36847f8026c6f', 'de...","[clone, dream, island, eye, dystopia, aging, f...",7.365935,37,21,Jean-Pierre Jeunet,0.096589
29,False,NaN,NaN,"[Drama, Crime]",NaN,37557,tt0115012,zh,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,...,6.5,17.0,"[Gong Li, Li Bao-Tian, Wang Xiaoxiao]","[{'credit_id': '52fe46559251416c910511c9', 'de...","[servant, cabaret, shanghai, diva, uncle, mist...",5.675302,6,4,Zhang Yimou,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46599,False,NaN,NaN,"[Action, Mystery, Thriller, Horror]",NaN,45527,tt1331329,en,The Final Storm,A stranger named Silas flees from a devastatin...,...,3.7,11.0,"[Lauren Holly, Luke Perry, Steve Bacic]","[{'credit_id': '52fe46c7c3a36847f81119a1', 'de...",[],4.837298,10,29,Uwe Boll,NaN
46600,False,NaN,NaN,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,en,In a Heartbeat,A closeted boy runs the risk of being outed by...,...,8.3,146.0,[],"[{'credit_id': '5981a15c92514151e0011b51', 'de...","[love, teenager, lgbt, short]",7.724949,0,7,Beth David,NaN
46601,False,NaN,NaN,[Drama],NaN,327237,tt3814486,nl,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",...,6.8,11.0,"[Martijn Fischer, Hadewych Minis, Fedja van Huêt]","[{'credit_id': '54edb0e0c3a3686d58003a13', 'de...","[biography, singer]",5.645993,5,2,Diederick Koopal,NaN
46602,False,NaN,NaN,"[Drama, Fantasy, Horror]",NaN,84710,tt0036975,en,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,...,5.8,2.0,"[Acquanetta, Evelyn Ankers, J. Carrol Naish]","[{'credit_id': '52fe49099251416c910a0a89', 'de...",[paula dupree],5.284208,13,2,Reginald Le Borg,NaN
46603,False,NaN,NaN,"[Drama, Family, TV Movie]",NaN,39562,tt0889600,en,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",...,5.0,12.0,"[Kaley Cuoco, Caroline Rhea, Melissa Halstrom]","[{'credit_id': '562ec44ec3a3681b5900bac2', 'de...","[overweight, independent film, prejudice, teen...",5.172674,7,2,Douglas Barr,NaN
46604,False,NaN,NaN,[Comedy],NaN,14008,tt0294425,en,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,...,5.2,145.0,"[Hilary Duff, Christy Carlson Romano, Gary Cole]","[{'credit_id': '52fe45c29251416c75061803', 'de...",[military school],5.207309,16,3,Larry Shaw,NaN
46605,False,NaN,NaN,[],NaN,44330,tt0135690,en,Le tripot clandestin,A combination gambling den and bawdy house is ...,...,5.0,3.0,[],"[{'credit_id': '52fe4684c3a36847f81034f3', 'de...",[police raid],5.213571,0,1,Georges Méliès,NaN
46606,False,NaN,NaN,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,fr,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,...,7.6,29.0,[Georges Méliès],"[{'credit_id': '52fe478dc3a36847f813bd5f', 'de...","[laboratory, mad scientist, disembodied head, ...",6.345558,1,3,Georges Méliès,NaN
46607,False,NaN,NaN,[Fantasy],NaN,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,...,6.1,8.0,[Georges Méliès],"[{'credit_id': '52fe4684c3a36847f810350b', 'de...","[magic, silent film, trick film]",5.418970,1,1,Georges Méliès,NaN
46608,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49277,tt0135122,en,Les affiches en goguette,A wall full of advertising posters comes to life.,...,4.5,2.0,[Georges Méliès],"[{'credit_id': '52fe478dc3a36847f813bd4b', 'de...","[silent film, acab]",5.178802,1,1,Georges Méliès,NaN
46609,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49271,tt0127948,en,Le locataire diabolique,A man rents an apartment and furnishes it in r...,...,6.7,12.0,"[André Méliès, Georges Méliès]","[{'credit_id': '52fe478dc3a36847f813bd19', 'de...","[tenant, silent film]",5.642887,2,1,Georges Méliès,NaN
46610,False,NaN,NaN,[],NaN,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,...,6.0,6.0,[Georges Méliès],"[{'credit_id': '52fe4684c3a36847f810345f', 'de...",[],5.368675,1,1,Georges Méliès,NaN
46611,False,NaN,NaN,[],NaN,122036,tt0224286,fr,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,...,5.0,2.0,[],"[{'credit_id': '52fe4a74c3a368484e1542e9', 'de...",[],5.219343,0,1,Georges Méliès,NaN
46612,False,NaN,NaN,"[Animation, Family]",NaN,14885,tt0457437,en,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",...,5.4,7.0,"[Jimmy Bennett, Peter Cullen, Jim Cummings]","[{'credit_id': '52fe46249251416c7506e969', 'de...","[halloween, winnie the pooh]",5.269421,11,6,Saul Blinkoff,NaN
46613,False,NaN,NaN,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,...,6.5,22.0,[Georges Méliès],"[{'credit_id': '52fe478dc3a36847f813bd6b', 'de...",[],5.747644,1,1,Georges Méliès,NaN
46614,False,NaN,NaN,"[Comedy, Fantasy]",NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,...,6.5,6.0,"[Jeanne d'Alcy, Georges Méliès]","[{'credit_id': '52fe4a71c3a36847f81ce35b', 'de...","[wrestling, sport, silent film, short, fat man]",5.454041,2,1,Georges Méliès,NaN
46615,False,NaN,NaN,[Documentary],NaN,276895,tt3054038,en,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",...,0.0,0.0,[],"[{'credit_id': '539ef1090e0a263dd00000d7', 'de...",[],5.089020,0,4,Robert Gardner,NaN
46616,False,NaN,NaN,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,...,6.6,14.0,"[Sridevi Kapoor, Sajal Ali, Akshaye Khanna]","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de...","[physical abuse, sexual assault]",5.655422,8,17,Ravi Udyawar,NaN
46617,False,NaN,NaN,"[Comedy, Drama]",NaN,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,...,4.0,2.0,"[Markie Adams, Roberto Aguire, Tina Arning]","[{'credit_id': '587626f4c3a3682b33008299', 'de...",[],5.138262,10,2,Shanra J. Kehl,NaN
46618,False,NaN,NaN,[],NaN,67179,tt0069215,it,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,...,6.0,3.0,"[Giulio Brogi, Renato Cestiè, Vito Cipolla]","[{'credit_id': '5330178a9251413a720055e3', 'de...",[],5.318834,4,4,Paolo Taviani,NaN
46619,False,NaN,NaN,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,...,6.3,8.0,"[Rondo Hatton, Robert Lowery, Virginia Grey]","[{'credit_id': '58152c139251415a7f0047e2', 'de...","[revenge, murder, serial killer, new york city...",5.460830,11,11,Jean Yarbrough,NaN
46620,False,NaN,NaN,"[Mystery, Horror]",NaN,390959,tt0265736,en,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",...,7.0,2.0,"[Tony Abatemarco, Andre Brooks, Mariclare Cost...","[{'credit_id': '56ff6ddbc3a3686e9e0013bc', 'de...",[blair witch],5.381505,19,29,Ben Rock,NaN
46621,False,NaN,NaN,[Horror],NaN,289923,tt0252966,en,The Burkittsville 7,A film archivist revisits the story of Rustin ...,...,7.0,1.0,"[Monty Bane, Lucy Butler, David Grammer]","[{'credit_id': '5403d669c3a3682d9800427d', 'de...","[witch, mythology, legend, serial killer, mock...",5.336547,8,2,Ben Rock,NaN
46622,False,NaN,NaN,[Science Fiction],NaN,222848,tt0112613,en,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,...,3.5,1.0,"[Lisa Boyle, Kena Land, Zaneta Polard]","[{'credit_id': '5757f36ac3a3687d6f000e8a', 'de...",[],5.142103,10,6,Aaron Osborne,NaN
46623,False,NaN,NaN,"[Drama, Action, Romance]",NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",...,5.7,26.0,"[Patrick Bergin, Uma Thurman, David Morrissey]","[{'credit_id': '52fe44439251416c9100a899', 'de...",[],5.442880,5,9,John Irvin,NaN
46624,False,NaN,NaN,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,4.0,1.0,"[Leila Hatami, Kourosh Tahami, Elham Korda]","[{'credit_id': '5894a97d925141426c00818c', 'de...",[tragic love],5.169880,3,9,Hamid Nematollah,NaN
46625,False,NaN,NaN,[Drama],NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,9.0,3.0,"[Angel Aquino, Perry Dizon, Hazel Orencio]","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...","[artist, play, pinoy]",5.634623,11,6,Lav Diaz,NaN
46626,False,NaN,NaN,"[Action, Drama, Thriller]",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,3.8,6.0,"[Erika Eleniak, Adam Baldwin, Julie du Page]","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",[],4.993066,15,5,Mark L. Lester,NaN
46627,False,NaN,NaN,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0.0,0.0,"[Iwan Mosschuchin, Nathalie Lissenko, Pavel Pa...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",[],5.089020,5,2,Yakov Protazanov,NaN
46628,False,NaN,NaN,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0.0,0.0,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",[],5.089020,0,1,Daisy Asquith,NaN

In [282]:
df.to_csv("movies_Merged_Alldata.csv.gz",index=False,compression="gzip")

# Converting to Dummies 

genres, director, original_language, production_companies, production_countries, cast, crew, keywords

In [283]:
from collections import Counter

# Find top 50 actors who appear most frequently
counter = Counter([item for sublist in df['cast'].values for item in sublist])
top_actors = counter.most_common(50)

In [284]:
# For each movie, check whether a top-50 actor appeared
for name, count in top_actors:
    print(name)
    
    for index, row in df.iterrows():
        list_of_names = row['cast']
    
        if name in list_of_names:
            df['cast_'+name] = 1
        else:
            df['cast_'+name] = 0

John Wayne
Jackie Chan
Robert De Niro
Michael Caine
Gérard Depardieu
Christopher Lee
Nicolas Cage
Harvey Keitel
Jeff Bridges
James Mason
Bette Davis
Samuel L. Jackson
Susan Sarandon
Donald Sutherland
Burt Lancaster
Bruce Willis
Burt Reynolds
Gene Hackman
Cary Grant
Marcello Mastroianni
James Stewart
Henry Fonda
Anthony Quinn
Eric Roberts
Gary Cooper
Barbara Stanwyck
Kirk Douglas
Robert Mitchum
Morgan Freeman
Catherine Deneuve
Helen Mirren
Paul Newman
Alec Baldwin
Christopher Walken
Boris Karloff
Vincent Price
Dolph Lundgren
Antonio Banderas
John Cusack
Meryl Streep
James Caan
Joan Crawford
James Franco
Akshay Kumar
Tom Hanks
Robin Williams
Val Kilmer
Julianne Moore
Isabelle Huppert
Robert Duvall

In [285]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,cast_James Caan,cast_Joan Crawford,cast_James Franco,cast_Akshay Kumar,cast_Tom Hanks,cast_Robin Williams,cast_Val Kilmer,cast_Julianne Moore,cast_Isabelle Huppert,cast_Robert Duvall
0,False,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,0,0,0,0,0,0,0,0,0,0
1,False,NaN,65000000.0,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,0,0,0,0,0,0,0,0,0,0
2,False,Grumpy Old Men Collection,NaN,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0,0,0,0,0,0,0,0,0,0
3,False,NaN,16000000.0,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,0,0,0,0,0,0,0,0,0,0
4,False,Father of the Bride Collection,NaN,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,0,0,0,0,0,0,0,0,0,0
5,False,NaN,60000000.0,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,0,0,0,0,0,0,0,0,0,0
6,False,NaN,58000000.0,"[Comedy, Romance]",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,0,0,0,0,0,0,0,0,0,0
7,False,NaN,NaN,"[Action, Adventure, Drama, Family]",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",...,0,0,0,0,0,0,0,0,0,0
8,False,NaN,35000000.0,"[Action, Adventure, Thriller]",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,...,0,0,0,0,0,0,0,0,0,0
9,False,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,0,0,0,0,0,0,0,0,0,0
10,False,NaN,62000000.0,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,0,0,0,0,0,0,0,0,0,0
11,False,NaN,NaN,"[Comedy, Horror]",NaN,12110,tt0112896,en,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,...,0,0,0,0,0,0,0,0,0,0
12,False,Balto Collection,NaN,"[Family, Animation, Adventure]",NaN,21032,tt0112453,en,Balto,An outcast half-wolf risks his life to prevent...,...,0,0,0,0,0,0,0,0,0,0
13,False,NaN,44000000.0,"[History, Drama]",NaN,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,0,0,0,0,0,0,0,0,0,0
14,False,NaN,98000000.0,"[Action, Adventure]",NaN,1408,tt0112760,en,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",...,0,0,0,0,0,0,0,0,0,0
15,False,NaN,52000000.0,"[Drama, Crime]",NaN,524,tt0112641,en,Casino,The life of the gambling paradise – Las Vegas ...,...,0,0,0,0,0,0,0,0,0,0
16,False,NaN,16500000.0,"[Drama, Romance]",NaN,4584,tt0114388,en,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",...,0,0,0,0,0,0,0,0,0,0
17,False,NaN,4000000.0,"[Crime, Comedy]",NaN,5,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,...,0,0,0,0,0,0,0,0,0,0
18,False,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,en,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",...,0,0,0,0,0,0,0,0,0,0
19,False,NaN,60000000.0,"[Action, Comedy, Crime]",NaN,11517,tt0113845,en,Money Train,A vengeful New York transit cop decides to ste...,...,0,0,0,0,0,0,0,0,0,0
20,False,Chili Palmer Collection,30250000.0,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,en,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,...,0,0,0,0,0,0,0,0,0,0
21,False,NaN,NaN,"[Drama, Thriller]",NaN,1710,tt0112722,en,Copycat,An agoraphobic psychologist and a female detec...,...,0,0,0,0,0,0,0,0,0,0
22,False,NaN,50000000.0,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,en,Assassins,Assassin Robert Rath arrives at a funeral to k...,...,0,0,0,0,0,0,0,0,0,0
23,False,NaN,NaN,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,en,Powder,Harassed by classmates who won't accept his sh...,...,0,0,0,0,0,0,0,0,0,0
24,False,NaN,3600000.0,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",...,0,0,0,0,0,0,0,0,0,0
25,False,NaN,NaN,[Drama],NaN,16420,tt0114057,en,Othello,The evil Iago pretends to be friend of Othello...,...,0,0,0,0,0,0,0,0,0,0
26,False,NaN,12000000.0,"[Comedy, Drama, Family]",NaN,9263,tt0114011,en,Now and Then,Waxing nostalgic about the bittersweet passage...,...,0,0,0,0,0,0,0,0,0,0
27,False,NaN,NaN,"[Drama, Romance]",NaN,17015,tt0114117,en,Persuasion,This film adaptation of Jane Austen's last nov...,...,0,0,0,0,0,0,0,0,0,0
28,False,NaN,18000000.0,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,fr,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,...,0,0,0,0,0,0,0,0,0,0
29,False,NaN,NaN,"[Drama, Crime]",NaN,37557,tt0115012,zh,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46599,False,NaN,NaN,"[Action, Mystery, Thriller, Horror]",NaN,45527,tt1331329,en,The Final Storm,A stranger named Silas flees from a devastatin...,...,0,0,0,0,0,0,0,0,0,0
46600,False,NaN,NaN,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,en,In a Heartbeat,A closeted boy runs the risk of being outed by...,...,0,0,0,0,0,0,0,0,0,0
46601,False,NaN,NaN,[Drama],NaN,327237,tt3814486,nl,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",...,0,0,0,0,0,0,0,0,0,0
46602,False,NaN,NaN,"[Drama, Fantasy, Horror]",NaN,84710,tt0036975,en,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,...,0,0,0,0,0,0,0,0,0,0
46603,False,NaN,NaN,"[Drama, Family, TV Movie]",NaN,39562,tt0889600,en,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",...,0,0,0,0,0,0,0,0,0,0
46604,False,NaN,NaN,[Comedy],NaN,14008,tt0294425,en,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,...,0,0,0,0,0,0,0,0,0,0
46605,False,NaN,NaN,[],NaN,44330,tt0135690,en,Le tripot clandestin,A combination gambling den and bawdy house is ...,...,0,0,0,0,0,0,0,0,0,0
46606,False,NaN,NaN,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,fr,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,...,0,0,0,0,0,0,0,0,0,0
46607,False,NaN,NaN,[Fantasy],NaN,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,...,0,0,0,0,0,0,0,0,0,0
46608,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49277,tt0135122,en,Les affiches en goguette,A wall full of advertising posters comes to life.,...,0,0,0,0,0,0,0,0,0,0
46609,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49271,tt0127948,en,Le locataire diabolique,A man rents an apartment and furnishes it in r...,...,0,0,0,0,0,0,0,0,0,0
46610,False,NaN,NaN,[],NaN,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,...,0,0,0,0,0,0,0,0,0,0
46611,False,NaN,NaN,[],NaN,122036,tt0224286,fr,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,...,0,0,0,0,0,0,0,0,0,0
46612,False,NaN,NaN,"[Animation, Family]",NaN,14885,tt0457437,en,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",...,0,0,0,0,0,0,0,0,0,0
46613,False,NaN,NaN,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,...,0,0,0,0,0,0,0,0,0,0
46614,False,NaN,NaN,"[Comedy, Fantasy]",NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,...,0,0,0,0,0,0,0,0,0,0
46615,False,NaN,NaN,[Documentary],NaN,276895,tt3054038,en,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",...,0,0,0,0,0,0,0,0,0,0
46616,False,NaN,NaN,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,...,0,0,0,0,0,0,0,0,0,0
46617,False,NaN,NaN,"[Comedy, Drama]",NaN,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,...,0,0,0,0,0,0,0,0,0,0
46618,False,NaN,NaN,[],NaN,67179,tt0069215,it,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,...,0,0,0,0,0,0,0,0,0,0
46619,False,NaN,NaN,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,...,0,0,0,0,0,0,0,0,0,0
46620,False,NaN,NaN,"[Mystery, Horror]",NaN,390959,tt0265736,en,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",...,0,0,0,0,0,0,0,0,0,0
46621,False,NaN,NaN,[Horror],NaN,289923,tt0252966,en,The Burkittsville 7,A film archivist revisits the story of Rustin ...,...,0,0,0,0,0,0,0,0,0,0
46622,False,NaN,NaN,[Science Fiction],NaN,222848,tt0112613,en,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,...,0,0,0,0,0,0,0,0,0,0
46623,False,NaN,NaN,"[Drama, Action, Romance]",NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",...,0,0,0,0,0,0,0,0,0,0
46624,False,NaN,NaN,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,0,0,0,0,0,0,0,0,0,0
46625,False,NaN,NaN,[Drama],NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,0,0,0,0,0,0,0,0,0,0
46626,False,NaN,NaN,"[Action, Drama, Thriller]",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,0,0,0,0,0,0,0,0,0,0
46627,False,NaN,NaN,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0,0,0,0,0,0,0,0,0,0
46628,False,NaN,NaN,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0,0,0,0,0,0,0,0,0,0

In [286]:
# Find top 50 genres which are most poplular
counter = Counter([item for sublist in df['genres'].values for item in sublist])
top_genres = counter.most_common(50)

In [287]:
# For each movie, check whether a top-50 genres
for name, count in top_genres:
    print(name)
    
    for index, row in df.iterrows():
        list_of_names = row['genres']
    
        if name in list_of_names:
            df['genres'+name] = 1
        else:
            df['genres'+name] = 0

Drama
Comedy
Thriller
Romance
Action
Horror
Crime
Documentary
Adventure
Science Fiction
Family
Mystery
Fantasy
Animation
Foreign
Music
History
War
Western
TV Movie

In [288]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,genresFamily,genresMystery,genresFantasy,genresAnimation,genresForeign,genresMusic,genresHistory,genresWar,genresWestern,genresTV Movie
0,False,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,0,0,0,0,0,0,0,0,0,0
1,False,NaN,65000000.0,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,0,0,0,0,0,0,0,0,0,0
2,False,Grumpy Old Men Collection,NaN,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0,0,0,0,0,0,0,0,0,0
3,False,NaN,16000000.0,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,0,0,0,0,0,0,0,0,0,0
4,False,Father of the Bride Collection,NaN,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,0,0,0,0,0,0,0,0,0,0
5,False,NaN,60000000.0,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,0,0,0,0,0,0,0,0,0,0
6,False,NaN,58000000.0,"[Comedy, Romance]",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,0,0,0,0,0,0,0,0,0,0
7,False,NaN,NaN,"[Action, Adventure, Drama, Family]",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",...,0,0,0,0,0,0,0,0,0,0
8,False,NaN,35000000.0,"[Action, Adventure, Thriller]",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,...,0,0,0,0,0,0,0,0,0,0
9,False,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,0,0,0,0,0,0,0,0,0,0
10,False,NaN,62000000.0,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,0,0,0,0,0,0,0,0,0,0
11,False,NaN,NaN,"[Comedy, Horror]",NaN,12110,tt0112896,en,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,...,0,0,0,0,0,0,0,0,0,0
12,False,Balto Collection,NaN,"[Family, Animation, Adventure]",NaN,21032,tt0112453,en,Balto,An outcast half-wolf risks his life to prevent...,...,0,0,0,0,0,0,0,0,0,0
13,False,NaN,44000000.0,"[History, Drama]",NaN,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,0,0,0,0,0,0,0,0,0,0
14,False,NaN,98000000.0,"[Action, Adventure]",NaN,1408,tt0112760,en,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",...,0,0,0,0,0,0,0,0,0,0
15,False,NaN,52000000.0,"[Drama, Crime]",NaN,524,tt0112641,en,Casino,The life of the gambling paradise – Las Vegas ...,...,0,0,0,0,0,0,0,0,0,0
16,False,NaN,16500000.0,"[Drama, Romance]",NaN,4584,tt0114388,en,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",...,0,0,0,0,0,0,0,0,0,0
17,False,NaN,4000000.0,"[Crime, Comedy]",NaN,5,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,...,0,0,0,0,0,0,0,0,0,0
18,False,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,en,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",...,0,0,0,0,0,0,0,0,0,0
19,False,NaN,60000000.0,"[Action, Comedy, Crime]",NaN,11517,tt0113845,en,Money Train,A vengeful New York transit cop decides to ste...,...,0,0,0,0,0,0,0,0,0,0
20,False,Chili Palmer Collection,30250000.0,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,en,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,...,0,0,0,0,0,0,0,0,0,0
21,False,NaN,NaN,"[Drama, Thriller]",NaN,1710,tt0112722,en,Copycat,An agoraphobic psychologist and a female detec...,...,0,0,0,0,0,0,0,0,0,0
22,False,NaN,50000000.0,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,en,Assassins,Assassin Robert Rath arrives at a funeral to k...,...,0,0,0,0,0,0,0,0,0,0
23,False,NaN,NaN,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,en,Powder,Harassed by classmates who won't accept his sh...,...,0,0,0,0,0,0,0,0,0,0
24,False,NaN,3600000.0,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",...,0,0,0,0,0,0,0,0,0,0
25,False,NaN,NaN,[Drama],NaN,16420,tt0114057,en,Othello,The evil Iago pretends to be friend of Othello...,...,0,0,0,0,0,0,0,0,0,0
26,False,NaN,12000000.0,"[Comedy, Drama, Family]",NaN,9263,tt0114011,en,Now and Then,Waxing nostalgic about the bittersweet passage...,...,0,0,0,0,0,0,0,0,0,0
27,False,NaN,NaN,"[Drama, Romance]",NaN,17015,tt0114117,en,Persuasion,This film adaptation of Jane Austen's last nov...,...,0,0,0,0,0,0,0,0,0,0
28,False,NaN,18000000.0,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,fr,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,...,0,0,0,0,0,0,0,0,0,0
29,False,NaN,NaN,"[Drama, Crime]",NaN,37557,tt0115012,zh,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46599,False,NaN,NaN,"[Action, Mystery, Thriller, Horror]",NaN,45527,tt1331329,en,The Final Storm,A stranger named Silas flees from a devastatin...,...,0,0,0,0,0,0,0,0,0,0
46600,False,NaN,NaN,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,en,In a Heartbeat,A closeted boy runs the risk of being outed by...,...,0,0,0,0,0,0,0,0,0,0
46601,False,NaN,NaN,[Drama],NaN,327237,tt3814486,nl,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",...,0,0,0,0,0,0,0,0,0,0
46602,False,NaN,NaN,"[Drama, Fantasy, Horror]",NaN,84710,tt0036975,en,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,...,0,0,0,0,0,0,0,0,0,0
46603,False,NaN,NaN,"[Drama, Family, TV Movie]",NaN,39562,tt0889600,en,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",...,0,0,0,0,0,0,0,0,0,0
46604,False,NaN,NaN,[Comedy],NaN,14008,tt0294425,en,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,...,0,0,0,0,0,0,0,0,0,0
46605,False,NaN,NaN,[],NaN,44330,tt0135690,en,Le tripot clandestin,A combination gambling den and bawdy house is ...,...,0,0,0,0,0,0,0,0,0,0
46606,False,NaN,NaN,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,fr,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,...,0,0,0,0,0,0,0,0,0,0
46607,False,NaN,NaN,[Fantasy],NaN,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,...,0,0,0,0,0,0,0,0,0,0
46608,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49277,tt0135122,en,Les affiches en goguette,A wall full of advertising posters comes to life.,...,0,0,0,0,0,0,0,0,0,0
46609,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49271,tt0127948,en,Le locataire diabolique,A man rents an apartment and furnishes it in r...,...,0,0,0,0,0,0,0,0,0,0
46610,False,NaN,NaN,[],NaN,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,...,0,0,0,0,0,0,0,0,0,0
46611,False,NaN,NaN,[],NaN,122036,tt0224286,fr,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,...,0,0,0,0,0,0,0,0,0,0
46612,False,NaN,NaN,"[Animation, Family]",NaN,14885,tt0457437,en,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",...,0,0,0,0,0,0,0,0,0,0
46613,False,NaN,NaN,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,...,0,0,0,0,0,0,0,0,0,0
46614,False,NaN,NaN,"[Comedy, Fantasy]",NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,...,0,0,0,0,0,0,0,0,0,0
46615,False,NaN,NaN,[Documentary],NaN,276895,tt3054038,en,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",...,0,0,0,0,0,0,0,0,0,0
46616,False,NaN,NaN,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,...,0,0,0,0,0,0,0,0,0,0
46617,False,NaN,NaN,"[Comedy, Drama]",NaN,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,...,0,0,0,0,0,0,0,0,0,0
46618,False,NaN,NaN,[],NaN,67179,tt0069215,it,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,...,0,0,0,0,0,0,0,0,0,0
46619,False,NaN,NaN,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,...,0,0,0,0,0,0,0,0,0,0
46620,False,NaN,NaN,"[Mystery, Horror]",NaN,390959,tt0265736,en,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",...,0,0,0,0,0,0,0,0,0,0
46621,False,NaN,NaN,[Horror],NaN,289923,tt0252966,en,The Burkittsville 7,A film archivist revisits the story of Rustin ...,...,0,0,0,0,0,0,0,0,0,0
46622,False,NaN,NaN,[Science Fiction],NaN,222848,tt0112613,en,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,...,0,0,0,0,0,0,0,0,0,0
46623,False,NaN,NaN,"[Drama, Action, Romance]",NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",...,0,0,0,0,0,0,0,0,0,0
46624,False,NaN,NaN,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,0,0,0,0,0,0,0,0,0,0
46625,False,NaN,NaN,[Drama],NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,0,0,0,0,0,0,0,0,0,0
46626,False,NaN,NaN,"[Action, Drama, Thriller]",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,0,0,0,0,0,0,0,0,0,0
46627,False,NaN,NaN,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0,0,0,0,0,0,0,0,0,0
46628,False,NaN,NaN,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0,0,0,0,0,0,0,0,0,0

In [289]:
# Find top 50 keywords which are most poplular
counter = Counter([item for sublist in df['keywords'].values for item in sublist])
top_keywords = counter.most_common(50)

In [290]:
# For each keyword, check whether a top-50 keywords
for name, count in top_keywords:
    print(name)
    
    for index, row in df.iterrows():
        list_of_names = row['keywords']
    
        if name in list_of_names:
            df['keywords'+name] = 1
        else:
            df['keywords'+name] = 0

woman director
independent film
murder
based on novel
musical
sex
violence
biography
nudity
revenge
suspense
love
female nudity
sport
police
sequel
teenager
duringcreditsstinger
friendship
world war ii
drug
prison
stand-up comedy
high school
martial arts
suicide
film noir
rape
kidnapping
silent film
family
serial killer
monster
alien
paris
dystopia
new york
gay
blood
marriage
short
christmas
gore
death
zombie
gangster
small town
london england
romance
male nudity

In [291]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,keywordsshort,keywordschristmas,keywordsgore,keywordsdeath,keywordszombie,keywordsgangster,keywordssmall town,keywordslondon england,keywordsromance,keywordsmale nudity
0,False,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,0,0,0,0,0,0,0,0,0,0
1,False,NaN,65000000.0,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,0,0,0,0,0,0,0,0,0,0
2,False,Grumpy Old Men Collection,NaN,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0,0,0,0,0,0,0,0,0,0
3,False,NaN,16000000.0,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,0,0,0,0,0,0,0,0,0,0
4,False,Father of the Bride Collection,NaN,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,0,0,0,0,0,0,0,0,0,0
5,False,NaN,60000000.0,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,0,0,0,0,0,0,0,0,0,0
6,False,NaN,58000000.0,"[Comedy, Romance]",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,0,0,0,0,0,0,0,0,0,0
7,False,NaN,NaN,"[Action, Adventure, Drama, Family]",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",...,0,0,0,0,0,0,0,0,0,0
8,False,NaN,35000000.0,"[Action, Adventure, Thriller]",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,...,0,0,0,0,0,0,0,0,0,0
9,False,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,0,0,0,0,0,0,0,0,0,0
10,False,NaN,62000000.0,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,en,The American President,"Widowed U.S. president Andrew Shepherd, one of...",...,0,0,0,0,0,0,0,0,0,0
11,False,NaN,NaN,"[Comedy, Horror]",NaN,12110,tt0112896,en,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,...,0,0,0,0,0,0,0,0,0,0
12,False,Balto Collection,NaN,"[Family, Animation, Adventure]",NaN,21032,tt0112453,en,Balto,An outcast half-wolf risks his life to prevent...,...,0,0,0,0,0,0,0,0,0,0
13,False,NaN,44000000.0,"[History, Drama]",NaN,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,0,0,0,0,0,0,0,0,0,0
14,False,NaN,98000000.0,"[Action, Adventure]",NaN,1408,tt0112760,en,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",...,0,0,0,0,0,0,0,0,0,0
15,False,NaN,52000000.0,"[Drama, Crime]",NaN,524,tt0112641,en,Casino,The life of the gambling paradise – Las Vegas ...,...,0,0,0,0,0,0,0,0,0,0
16,False,NaN,16500000.0,"[Drama, Romance]",NaN,4584,tt0114388,en,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",...,0,0,0,0,0,0,0,0,0,0
17,False,NaN,4000000.0,"[Crime, Comedy]",NaN,5,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,...,0,0,0,0,0,0,0,0,0,0
18,False,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,en,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",...,0,0,0,0,0,0,0,0,0,0
19,False,NaN,60000000.0,"[Action, Comedy, Crime]",NaN,11517,tt0113845,en,Money Train,A vengeful New York transit cop decides to ste...,...,0,0,0,0,0,0,0,0,0,0
20,False,Chili Palmer Collection,30250000.0,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,en,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,...,0,0,0,0,0,0,0,0,0,0
21,False,NaN,NaN,"[Drama, Thriller]",NaN,1710,tt0112722,en,Copycat,An agoraphobic psychologist and a female detec...,...,0,0,0,0,0,0,0,0,0,0
22,False,NaN,50000000.0,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,en,Assassins,Assassin Robert Rath arrives at a funeral to k...,...,0,0,0,0,0,0,0,0,0,0
23,False,NaN,NaN,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,en,Powder,Harassed by classmates who won't accept his sh...,...,0,0,0,0,0,0,0,0,0,0
24,False,NaN,3600000.0,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,en,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",...,0,0,0,0,0,0,0,0,0,0
25,False,NaN,NaN,[Drama],NaN,16420,tt0114057,en,Othello,The evil Iago pretends to be friend of Othello...,...,0,0,0,0,0,0,0,0,0,0
26,False,NaN,12000000.0,"[Comedy, Drama, Family]",NaN,9263,tt0114011,en,Now and Then,Waxing nostalgic about the bittersweet passage...,...,0,0,0,0,0,0,0,0,0,0
27,False,NaN,NaN,"[Drama, Romance]",NaN,17015,tt0114117,en,Persuasion,This film adaptation of Jane Austen's last nov...,...,0,0,0,0,0,0,0,0,0,0
28,False,NaN,18000000.0,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,fr,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,...,0,0,0,0,0,0,0,0,0,0
29,False,NaN,NaN,"[Drama, Crime]",NaN,37557,tt0115012,zh,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46599,False,NaN,NaN,"[Action, Mystery, Thriller, Horror]",NaN,45527,tt1331329,en,The Final Storm,A stranger named Silas flees from a devastatin...,...,0,0,0,0,0,0,0,0,0,0
46600,False,NaN,NaN,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,en,In a Heartbeat,A closeted boy runs the risk of being outed by...,...,0,0,0,0,0,0,0,0,0,0
46601,False,NaN,NaN,[Drama],NaN,327237,tt3814486,nl,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",...,0,0,0,0,0,0,0,0,0,0
46602,False,NaN,NaN,"[Drama, Fantasy, Horror]",NaN,84710,tt0036975,en,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,...,0,0,0,0,0,0,0,0,0,0
46603,False,NaN,NaN,"[Drama, Family, TV Movie]",NaN,39562,tt0889600,en,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",...,0,0,0,0,0,0,0,0,0,0
46604,False,NaN,NaN,[Comedy],NaN,14008,tt0294425,en,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,...,0,0,0,0,0,0,0,0,0,0
46605,False,NaN,NaN,[],NaN,44330,tt0135690,en,Le tripot clandestin,A combination gambling den and bawdy house is ...,...,0,0,0,0,0,0,0,0,0,0
46606,False,NaN,NaN,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,fr,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,...,0,0,0,0,0,0,0,0,0,0
46607,False,NaN,NaN,[Fantasy],NaN,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,...,0,0,0,0,0,0,0,0,0,0
46608,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49277,tt0135122,en,Les affiches en goguette,A wall full of advertising posters comes to life.,...,0,0,0,0,0,0,0,0,0,0
46609,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49271,tt0127948,en,Le locataire diabolique,A man rents an apartment and furnishes it in r...,...,0,0,0,0,0,0,0,0,0,0
46610,False,NaN,NaN,[],NaN,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,...,0,0,0,0,0,0,0,0,0,0
46611,False,NaN,NaN,[],NaN,122036,tt0224286,fr,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,...,0,0,0,0,0,0,0,0,0,0
46612,False,NaN,NaN,"[Animation, Family]",NaN,14885,tt0457437,en,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",...,0,0,0,0,0,0,0,0,0,0
46613,False,NaN,NaN,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,...,0,0,0,0,0,0,0,0,0,0
46614,False,NaN,NaN,"[Comedy, Fantasy]",NaN,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,...,0,0,0,0,0,0,0,0,0,0
46615,False,NaN,NaN,[Documentary],NaN,276895,tt3054038,en,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",...,0,0,0,0,0,0,0,0,0,0
46616,False,NaN,NaN,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,...,0,0,0,0,0,0,0,0,0,0
46617,False,NaN,NaN,"[Comedy, Drama]",NaN,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,...,0,0,0,0,0,0,0,0,0,0
46618,False,NaN,NaN,[],NaN,67179,tt0069215,it,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,...,0,0,0,0,0,0,0,0,0,0
46619,False,NaN,NaN,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,...,0,0,0,0,0,0,0,0,0,0
46620,False,NaN,NaN,"[Mystery, Horror]",NaN,390959,tt0265736,en,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",...,0,0,0,0,0,0,0,0,0,0
46621,False,NaN,NaN,[Horror],NaN,289923,tt0252966,en,The Burkittsville 7,A film archivist revisits the story of Rustin ...,...,0,0,0,0,0,0,0,0,0,0
46622,False,NaN,NaN,[Science Fiction],NaN,222848,tt0112613,en,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,...,0,0,0,0,0,0,0,0,0,0
46623,False,NaN,NaN,"[Drama, Action, Romance]",NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",...,0,0,0,0,0,0,0,0,0,0
46624,False,NaN,NaN,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,0,0,0,0,0,0,0,0,0,0
46625,False,NaN,NaN,[Drama],NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,0,0,0,0,0,0,0,0,0,0
46626,False,NaN,NaN,"[Action, Drama, Thriller]",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,0,0,0,0,0,0,0,0,0,0
46627,False,NaN,NaN,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0,0,0,0,0,0,0,0,0,0
46628,False,NaN,NaN,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0,0,0,0,0,0,0,0,0,0

In [292]:
df = pd.get_dummies(df, columns=['original_language'])
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_title,overview,popularity,...,original_language_tl,original_language_tr,original_language_uk,original_language_ur,original_language_uz,original_language_vi,original_language_wo,original_language_xx,original_language_zh,original_language_zu
0,False,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,0,0,0,0,0,0,0,0,0,0
1,False,NaN,65000000.0,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,Jumanji,When siblings Judy and Peter discover an encha...,17.0155,...,0,0,0,0,0,0,0,0,0,0
2,False,Grumpy Old Men Collection,NaN,"[Romance, Comedy]",NaN,15602,tt0113228,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,0,0,0,0,0,0,0,0,0,0
3,False,NaN,16000000.0,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.85949,...,0,0,0,0,0,0,0,0,0,0
4,False,Father of the Bride Collection,NaN,[Comedy],NaN,11862,tt0113041,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.38752,...,0,0,0,0,0,0,0,0,0,0
5,False,NaN,60000000.0,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.9249,...,0,0,0,0,0,0,0,0,0,0
6,False,NaN,58000000.0,"[Comedy, Romance]",NaN,11860,tt0114319,Sabrina,An ugly duckling having undergone a remarkable...,6.67728,...,0,0,0,0,0,0,0,0,0,0
7,False,NaN,NaN,"[Action, Adventure, Drama, Family]",NaN,45325,tt0112302,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.56116,...,0,0,0,0,0,0,0,0,0,0
8,False,NaN,35000000.0,"[Action, Adventure, Thriller]",NaN,9091,tt0114576,Sudden Death,International action superstar Jean Claude Van...,5.23158,...,0,0,0,0,0,0,0,0,0,0
9,False,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,GoldenEye,James Bond must unmask the mysterious head of ...,14.686,...,0,0,0,0,0,0,0,0,0,0
10,False,NaN,62000000.0,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,The American President,"Widowed U.S. president Andrew Shepherd, one of...",6.31844,...,0,0,0,0,0,0,0,0,0,0
11,False,NaN,NaN,"[Comedy, Horror]",NaN,12110,tt0112896,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,5.43033,...,0,0,0,0,0,0,0,0,0,0
12,False,Balto Collection,NaN,"[Family, Animation, Adventure]",NaN,21032,tt0112453,Balto,An outcast half-wolf risks his life to prevent...,12.1407,...,0,0,0,0,0,0,0,0,0,0
13,False,NaN,44000000.0,"[History, Drama]",NaN,10858,tt0113987,Nixon,An all-star cast powers this epic look at Amer...,5.092,...,0,0,0,0,0,0,0,0,0,0
14,False,NaN,98000000.0,"[Action, Adventure]",NaN,1408,tt0112760,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",7.28448,...,0,0,0,0,0,0,0,0,0,0
15,False,NaN,52000000.0,"[Drama, Crime]",NaN,524,tt0112641,Casino,The life of the gambling paradise – Las Vegas ...,10.1374,...,0,0,0,0,0,0,0,0,0,0
16,False,NaN,16500000.0,"[Drama, Romance]",NaN,4584,tt0114388,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",10.6732,...,0,0,0,0,0,0,0,0,0,0
17,False,NaN,4000000.0,"[Crime, Comedy]",NaN,5,tt0113101,Four Rooms,It's Ted the Bellhop's first night on the job....,9.02659,...,0,0,0,0,0,0,0,0,0,0
18,False,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",8.20545,...,0,0,0,0,0,0,0,0,0,0
19,False,NaN,60000000.0,"[Action, Comedy, Crime]",NaN,11517,tt0113845,Money Train,A vengeful New York transit cop decides to ste...,7.33791,...,0,0,0,0,0,0,0,0,0,0
20,False,Chili Palmer Collection,30250000.0,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,12.6696,...,0,0,0,0,0,0,0,0,0,0
21,False,NaN,NaN,"[Drama, Thriller]",NaN,1710,tt0112722,Copycat,An agoraphobic psychologist and a female detec...,10.7018,...,0,0,0,0,0,0,0,0,0,0
22,False,NaN,50000000.0,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,Assassins,Assassin Robert Rath arrives at a funeral to k...,11.0659,...,0,0,0,0,0,0,0,0,0,0
23,False,NaN,NaN,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,Powder,Harassed by classmates who won't accept his sh...,12.1331,...,0,0,0,0,0,0,0,0,0,0
24,False,NaN,3600000.0,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",10.332,...,0,0,0,0,0,0,0,0,0,0
25,False,NaN,NaN,[Drama],NaN,16420,tt0114057,Othello,The evil Iago pretends to be friend of Othello...,1.8459,...,0,0,0,0,0,0,0,0,0,0
26,False,NaN,12000000.0,"[Comedy, Drama, Family]",NaN,9263,tt0114011,Now and Then,Waxing nostalgic about the bittersweet passage...,8.68132,...,0,0,0,0,0,0,0,0,0,0
27,False,NaN,NaN,"[Drama, Romance]",NaN,17015,tt0114117,Persuasion,This film adaptation of Jane Austen's last nov...,2.22843,...,0,0,0,0,0,0,0,0,0,0
28,False,NaN,18000000.0,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,9.82242,...,0,0,0,0,0,0,0,0,0,0
29,False,NaN,NaN,"[Drama, Crime]",NaN,37557,tt0115012,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,1.10091,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46599,False,NaN,NaN,"[Action, Mystery, Thriller, Horror]",NaN,45527,tt1331329,The Final Storm,A stranger named Silas flees from a devastatin...,1.270832,...,0,0,0,0,0,0,0,0,0,0
46600,False,NaN,NaN,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,In a Heartbeat,A closeted boy runs the risk of being outed by...,20.82178,...,0,0,0,0,0,0,0,0,0,0
46601,False,NaN,NaN,[Drama],NaN,327237,tt3814486,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",0.590087,...,0,0,0,0,0,0,0,0,0,0
46602,False,NaN,NaN,"[Drama, Fantasy, Horror]",NaN,84710,tt0036975,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,0.143223,...,0,0,0,0,0,0,0,0,0,0
46603,False,NaN,NaN,"[Drama, Family, TV Movie]",NaN,39562,tt0889600,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",0.767762,...,0,0,0,0,0,0,0,0,0,0
46604,False,NaN,NaN,[Comedy],NaN,14008,tt0294425,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,4.392389,...,0,0,0,0,0,0,0,0,0,0
46605,False,NaN,NaN,[],NaN,44330,tt0135690,Le tripot clandestin,A combination gambling den and bawdy house is ...,0.21926,...,0,0,0,0,0,0,0,0,0,0
46606,False,NaN,NaN,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,1.618458,...,0,0,0,0,0,0,0,0,0,0
46607,False,NaN,NaN,[Fantasy],NaN,44333,tt0135179,Les cartes vivantes,A bearded magician holds up a large playing ca...,0.208349,...,0,0,0,0,0,0,0,0,0,0
46608,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49277,tt0135122,Les affiches en goguette,A wall full of advertising posters comes to life.,0.148131,...,0,0,0,0,0,0,0,0,0,0
46609,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49271,tt0127948,Le locataire diabolique,A man rents an apartment and furnishes it in r...,0.725084,...,0,0,0,0,0,0,0,0,0,0
46610,False,NaN,NaN,[],NaN,44324,tt0135631,Le Roi du maquillage,The background of this picture represents a sc...,0.213973,...,0,0,0,0,0,0,0,0,0,0
46611,False,NaN,NaN,[],NaN,122036,tt0224286,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,0.071782,...,0,0,0,0,0,0,0,0,0,0
46612,False,NaN,NaN,"[Animation, Family]",NaN,14885,tt0457437,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",2.568495,...,0,0,0,0,0,0,0,0,0,0
46613,False,NaN,NaN,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,...,0,0,0,0,0,0,0,0,0,0
46614,False,NaN,NaN,"[Comedy, Fantasy]",NaN,106807,tt0135571,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,0.225432,...,0,0,0,0,0,0,0,0,0,0
46615,False,NaN,NaN,[Documentary],NaN,276895,tt3054038,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",0.011025,...,0,0,0,0,0,0,0,0,0,0
46616,False,NaN,NaN,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,Maa,The bliss of a biology teacher’s family life i...,1.559596,...,0,0,0,0,0,0,0,0,0,0
46617,False,NaN,NaN,"[Comedy, Drama]",NaN,420346,tt4130180,The Morning After,The Morning After is a feature film that consi...,0.139936,...,0,0,0,0,0,0,0,0,0,0
46618,False,NaN,NaN,[],NaN,67179,tt0069215,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,0.225051,...,0,0,0,0,0,0,0,0,0,0
46619,False,NaN,NaN,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,House of Horrors,An unsuccessful sculptor saves a madman named ...,0.222814,...,0,0,0,0,0,0,0,0,0,0
46620,False,NaN,NaN,"[Mystery, Horror]",NaN,390959,tt0265736,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",0.076061,...,0,0,0,0,0,0,0,0,0,0
46621,False,NaN,NaN,[Horror],NaN,289923,tt0252966,The Burkittsville 7,A film archivist revisits the story of Rustin ...,0.38645,...,0,0,0,0,0,0,0,0,0,0
46622,False,NaN,NaN,[Science Fiction],NaN,222848,tt0112613,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,0.661558,...,0,0,0,0,0,0,0,0,0,0
46623,False,NaN,NaN,"[Drama, Action, Romance]",NaN,30840,tt0102797,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,...,0,0,0,0,0,0,0,0,0,0
46624,False,NaN,NaN,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,رگ خواب,Rising and falling between a man and woman.,0.072051,...,0,0,0,0,0,0,0,0,0,0
46625,False,NaN,NaN,[Drama],NaN,111109,tt2028550,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,...,1,0,0,0,0,0,0,0,0,0
46626,False,NaN,NaN,"[Action, Drama, Thriller]",NaN,67758,tt0303758,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,...,0,0,0,0,0,0,0,0,0,0
46627,False,NaN,NaN,[],NaN,227506,tt0008536,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,...,0,0,0,0,0,0,0,0,0,0
46628,False,NaN,NaN,[],NaN,461257,tt6980792,Queerama,50 years after decriminalisation of homosexual...,0.163015,...,0,0,0,0,0,0,0,0,0,0

In [293]:
df = pd.get_dummies(df,columns=['director'])
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_title,overview,popularity,...,director_Геннадий Сокольский,director_Григорий Никулин,director_Михаил Калатозишвили,director_Михаил Пореченков,director_Федор Дмитриев,director_Ярополк Лапшин,director_پیمان معادی,director_塩谷 直義,director_杰森·莫玛,director_진모영
0,False,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,0,0,0,0,0,0,0,0,0,0
1,False,NaN,65000000.0,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,Jumanji,When siblings Judy and Peter discover an encha...,17.0155,...,0,0,0,0,0,0,0,0,0,0
2,False,Grumpy Old Men Collection,NaN,"[Romance, Comedy]",NaN,15602,tt0113228,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,0,0,0,0,0,0,0,0,0,0
3,False,NaN,16000000.0,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.85949,...,0,0,0,0,0,0,0,0,0,0
4,False,Father of the Bride Collection,NaN,[Comedy],NaN,11862,tt0113041,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.38752,...,0,0,0,0,0,0,0,0,0,0
5,False,NaN,60000000.0,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.9249,...,0,0,0,0,0,0,0,0,0,0
6,False,NaN,58000000.0,"[Comedy, Romance]",NaN,11860,tt0114319,Sabrina,An ugly duckling having undergone a remarkable...,6.67728,...,0,0,0,0,0,0,0,0,0,0
7,False,NaN,NaN,"[Action, Adventure, Drama, Family]",NaN,45325,tt0112302,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.56116,...,0,0,0,0,0,0,0,0,0,0
8,False,NaN,35000000.0,"[Action, Adventure, Thriller]",NaN,9091,tt0114576,Sudden Death,International action superstar Jean Claude Van...,5.23158,...,0,0,0,0,0,0,0,0,0,0
9,False,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,GoldenEye,James Bond must unmask the mysterious head of ...,14.686,...,0,0,0,0,0,0,0,0,0,0
10,False,NaN,62000000.0,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,The American President,"Widowed U.S. president Andrew Shepherd, one of...",6.31844,...,0,0,0,0,0,0,0,0,0,0
11,False,NaN,NaN,"[Comedy, Horror]",NaN,12110,tt0112896,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,5.43033,...,0,0,0,0,0,0,0,0,0,0
12,False,Balto Collection,NaN,"[Family, Animation, Adventure]",NaN,21032,tt0112453,Balto,An outcast half-wolf risks his life to prevent...,12.1407,...,0,0,0,0,0,0,0,0,0,0
13,False,NaN,44000000.0,"[History, Drama]",NaN,10858,tt0113987,Nixon,An all-star cast powers this epic look at Amer...,5.092,...,0,0,0,0,0,0,0,0,0,0
14,False,NaN,98000000.0,"[Action, Adventure]",NaN,1408,tt0112760,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",7.28448,...,0,0,0,0,0,0,0,0,0,0
15,False,NaN,52000000.0,"[Drama, Crime]",NaN,524,tt0112641,Casino,The life of the gambling paradise – Las Vegas ...,10.1374,...,0,0,0,0,0,0,0,0,0,0
16,False,NaN,16500000.0,"[Drama, Romance]",NaN,4584,tt0114388,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",10.6732,...,0,0,0,0,0,0,0,0,0,0
17,False,NaN,4000000.0,"[Crime, Comedy]",NaN,5,tt0113101,Four Rooms,It's Ted the Bellhop's first night on the job....,9.02659,...,0,0,0,0,0,0,0,0,0,0
18,False,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",8.20545,...,0,0,0,0,0,0,0,0,0,0
19,False,NaN,60000000.0,"[Action, Comedy, Crime]",NaN,11517,tt0113845,Money Train,A vengeful New York transit cop decides to ste...,7.33791,...,0,0,0,0,0,0,0,0,0,0
20,False,Chili Palmer Collection,30250000.0,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,12.6696,...,0,0,0,0,0,0,0,0,0,0
21,False,NaN,NaN,"[Drama, Thriller]",NaN,1710,tt0112722,Copycat,An agoraphobic psychologist and a female detec...,10.7018,...,0,0,0,0,0,0,0,0,0,0
22,False,NaN,50000000.0,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,Assassins,Assassin Robert Rath arrives at a funeral to k...,11.0659,...,0,0,0,0,0,0,0,0,0,0
23,False,NaN,NaN,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,Powder,Harassed by classmates who won't accept his sh...,12.1331,...,0,0,0,0,0,0,0,0,0,0
24,False,NaN,3600000.0,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",10.332,...,0,0,0,0,0,0,0,0,0,0
25,False,NaN,NaN,[Drama],NaN,16420,tt0114057,Othello,The evil Iago pretends to be friend of Othello...,1.8459,...,0,0,0,0,0,0,0,0,0,0
26,False,NaN,12000000.0,"[Comedy, Drama, Family]",NaN,9263,tt0114011,Now and Then,Waxing nostalgic about the bittersweet passage...,8.68132,...,0,0,0,0,0,0,0,0,0,0
27,False,NaN,NaN,"[Drama, Romance]",NaN,17015,tt0114117,Persuasion,This film adaptation of Jane Austen's last nov...,2.22843,...,0,0,0,0,0,0,0,0,0,0
28,False,NaN,18000000.0,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,9.82242,...,0,0,0,0,0,0,0,0,0,0
29,False,NaN,NaN,"[Drama, Crime]",NaN,37557,tt0115012,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,1.10091,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46599,False,NaN,NaN,"[Action, Mystery, Thriller, Horror]",NaN,45527,tt1331329,The Final Storm,A stranger named Silas flees from a devastatin...,1.270832,...,0,0,0,0,0,0,0,0,0,0
46600,False,NaN,NaN,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,In a Heartbeat,A closeted boy runs the risk of being outed by...,20.82178,...,0,0,0,0,0,0,0,0,0,0
46601,False,NaN,NaN,[Drama],NaN,327237,tt3814486,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",0.590087,...,0,0,0,0,0,0,0,0,0,0
46602,False,NaN,NaN,"[Drama, Fantasy, Horror]",NaN,84710,tt0036975,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,0.143223,...,0,0,0,0,0,0,0,0,0,0
46603,False,NaN,NaN,"[Drama, Family, TV Movie]",NaN,39562,tt0889600,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",0.767762,...,0,0,0,0,0,0,0,0,0,0
46604,False,NaN,NaN,[Comedy],NaN,14008,tt0294425,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,4.392389,...,0,0,0,0,0,0,0,0,0,0
46605,False,NaN,NaN,[],NaN,44330,tt0135690,Le tripot clandestin,A combination gambling den and bawdy house is ...,0.21926,...,0,0,0,0,0,0,0,0,0,0
46606,False,NaN,NaN,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,1.618458,...,0,0,0,0,0,0,0,0,0,0
46607,False,NaN,NaN,[Fantasy],NaN,44333,tt0135179,Les cartes vivantes,A bearded magician holds up a large playing ca...,0.208349,...,0,0,0,0,0,0,0,0,0,0
46608,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49277,tt0135122,Les affiches en goguette,A wall full of advertising posters comes to life.,0.148131,...,0,0,0,0,0,0,0,0,0,0
46609,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49271,tt0127948,Le locataire diabolique,A man rents an apartment and furnishes it in r...,0.725084,...,0,0,0,0,0,0,0,0,0,0
46610,False,NaN,NaN,[],NaN,44324,tt0135631,Le Roi du maquillage,The background of this picture represents a sc...,0.213973,...,0,0,0,0,0,0,0,0,0,0
46611,False,NaN,NaN,[],NaN,122036,tt0224286,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,0.071782,...,0,0,0,0,0,0,0,0,0,0
46612,False,NaN,NaN,"[Animation, Family]",NaN,14885,tt0457437,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",2.568495,...,0,0,0,0,0,0,0,0,0,0
46613,False,NaN,NaN,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,...,0,0,0,0,0,0,0,0,0,0
46614,False,NaN,NaN,"[Comedy, Fantasy]",NaN,106807,tt0135571,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,0.225432,...,0,0,0,0,0,0,0,0,0,0
46615,False,NaN,NaN,[Documentary],NaN,276895,tt3054038,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",0.011025,...,0,0,0,0,0,0,0,0,0,0
46616,False,NaN,NaN,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,Maa,The bliss of a biology teacher’s family life i...,1.559596,...,0,0,0,0,0,0,0,0,0,0
46617,False,NaN,NaN,"[Comedy, Drama]",NaN,420346,tt4130180,The Morning After,The Morning After is a feature film that consi...,0.139936,...,0,0,0,0,0,0,0,0,0,0
46618,False,NaN,NaN,[],NaN,67179,tt0069215,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,0.225051,...,0,0,0,0,0,0,0,0,0,0
46619,False,NaN,NaN,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,House of Horrors,An unsuccessful sculptor saves a madman named ...,0.222814,...,0,0,0,0,0,0,0,0,0,0
46620,False,NaN,NaN,"[Mystery, Horror]",NaN,390959,tt0265736,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",0.076061,...,0,0,0,0,0,0,0,0,0,0
46621,False,NaN,NaN,[Horror],NaN,289923,tt0252966,The Burkittsville 7,A film archivist revisits the story of Rustin ...,0.38645,...,0,0,0,0,0,0,0,0,0,0
46622,False,NaN,NaN,[Science Fiction],NaN,222848,tt0112613,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,0.661558,...,0,0,0,0,0,0,0,0,0,0
46623,False,NaN,NaN,"[Drama, Action, Romance]",NaN,30840,tt0102797,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,...,0,0,0,0,0,0,0,0,0,0
46624,False,NaN,NaN,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,رگ خواب,Rising and falling between a man and woman.,0.072051,...,0,0,0,0,0,0,0,0,0,0
46625,False,NaN,NaN,[Drama],NaN,111109,tt2028550,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,...,0,0,0,0,0,0,0,0,0,0
46626,False,NaN,NaN,"[Action, Drama, Thriller]",NaN,67758,tt0303758,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,...,0,0,0,0,0,0,0,0,0,0
46627,False,NaN,NaN,[],NaN,227506,tt0008536,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,...,0,0,0,0,0,0,0,0,0,0
46628,False,NaN,NaN,[],NaN,461257,tt6980792,Queerama,50 years after decriminalisation of homosexual...,0.163015,...,0,0,0,0,0,0,0,0,0,0

In [296]:
# Find top 50 genres which are most poplular
counter = Counter([item for sublist in df['production_countries'].values for item in sublist])
top_production_countries = counter.most_common(50)

In [297]:
# For each movie, check whether a top-50 actor appeared
for name, count in top_production_countries:
    print(name)
    
    for index, row in df.iterrows():
        list_of_names = row['genres']
    
        if name in list_of_names:
            df['production_countries'+name] = 1
        else:
            df['production_countries'+name] = 0

United States of America
United Kingdom
France
Germany
Italy
Canada
Japan
Spain
Russia
India
Sweden
Hong Kong
Australia
South Korea
Belgium
Finland
Denmark
China
Netherlands
Mexico
Poland
Brazil
Argentina
Switzerland
Ireland
Norway
Austria
Czech Republic
Hungary
Greece
Turkey
Israel
Romania
Portugal
Taiwan
South Africa
Thailand
New Zealand
Iran
Serbia
Luxembourg
Philippines
Croatia
Chile
Iceland
Estonia
Bulgaria
Ukraine
Singapore
Colombia

In [298]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_title,overview,popularity,...,production_countriesLuxembourg,production_countriesPhilippines,production_countriesCroatia,production_countriesChile,production_countriesIceland,production_countriesEstonia,production_countriesBulgaria,production_countriesUkraine,production_countriesSingapore,production_countriesColombia
0,False,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,0,0,0,0,0,0,0,0,0,0
1,False,NaN,65000000.0,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,Jumanji,When siblings Judy and Peter discover an encha...,17.0155,...,0,0,0,0,0,0,0,0,0,0
2,False,Grumpy Old Men Collection,NaN,"[Romance, Comedy]",NaN,15602,tt0113228,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,0,0,0,0,0,0,0,0,0,0
3,False,NaN,16000000.0,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.85949,...,0,0,0,0,0,0,0,0,0,0
4,False,Father of the Bride Collection,NaN,[Comedy],NaN,11862,tt0113041,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.38752,...,0,0,0,0,0,0,0,0,0,0
5,False,NaN,60000000.0,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.9249,...,0,0,0,0,0,0,0,0,0,0
6,False,NaN,58000000.0,"[Comedy, Romance]",NaN,11860,tt0114319,Sabrina,An ugly duckling having undergone a remarkable...,6.67728,...,0,0,0,0,0,0,0,0,0,0
7,False,NaN,NaN,"[Action, Adventure, Drama, Family]",NaN,45325,tt0112302,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.56116,...,0,0,0,0,0,0,0,0,0,0
8,False,NaN,35000000.0,"[Action, Adventure, Thriller]",NaN,9091,tt0114576,Sudden Death,International action superstar Jean Claude Van...,5.23158,...,0,0,0,0,0,0,0,0,0,0
9,False,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,GoldenEye,James Bond must unmask the mysterious head of ...,14.686,...,0,0,0,0,0,0,0,0,0,0
10,False,NaN,62000000.0,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,The American President,"Widowed U.S. president Andrew Shepherd, one of...",6.31844,...,0,0,0,0,0,0,0,0,0,0
11,False,NaN,NaN,"[Comedy, Horror]",NaN,12110,tt0112896,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,5.43033,...,0,0,0,0,0,0,0,0,0,0
12,False,Balto Collection,NaN,"[Family, Animation, Adventure]",NaN,21032,tt0112453,Balto,An outcast half-wolf risks his life to prevent...,12.1407,...,0,0,0,0,0,0,0,0,0,0
13,False,NaN,44000000.0,"[History, Drama]",NaN,10858,tt0113987,Nixon,An all-star cast powers this epic look at Amer...,5.092,...,0,0,0,0,0,0,0,0,0,0
14,False,NaN,98000000.0,"[Action, Adventure]",NaN,1408,tt0112760,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",7.28448,...,0,0,0,0,0,0,0,0,0,0
15,False,NaN,52000000.0,"[Drama, Crime]",NaN,524,tt0112641,Casino,The life of the gambling paradise – Las Vegas ...,10.1374,...,0,0,0,0,0,0,0,0,0,0
16,False,NaN,16500000.0,"[Drama, Romance]",NaN,4584,tt0114388,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",10.6732,...,0,0,0,0,0,0,0,0,0,0
17,False,NaN,4000000.0,"[Crime, Comedy]",NaN,5,tt0113101,Four Rooms,It's Ted the Bellhop's first night on the job....,9.02659,...,0,0,0,0,0,0,0,0,0,0
18,False,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",8.20545,...,0,0,0,0,0,0,0,0,0,0
19,False,NaN,60000000.0,"[Action, Comedy, Crime]",NaN,11517,tt0113845,Money Train,A vengeful New York transit cop decides to ste...,7.33791,...,0,0,0,0,0,0,0,0,0,0
20,False,Chili Palmer Collection,30250000.0,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,12.6696,...,0,0,0,0,0,0,0,0,0,0
21,False,NaN,NaN,"[Drama, Thriller]",NaN,1710,tt0112722,Copycat,An agoraphobic psychologist and a female detec...,10.7018,...,0,0,0,0,0,0,0,0,0,0
22,False,NaN,50000000.0,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,Assassins,Assassin Robert Rath arrives at a funeral to k...,11.0659,...,0,0,0,0,0,0,0,0,0,0
23,False,NaN,NaN,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,Powder,Harassed by classmates who won't accept his sh...,12.1331,...,0,0,0,0,0,0,0,0,0,0
24,False,NaN,3600000.0,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",10.332,...,0,0,0,0,0,0,0,0,0,0
25,False,NaN,NaN,[Drama],NaN,16420,tt0114057,Othello,The evil Iago pretends to be friend of Othello...,1.8459,...,0,0,0,0,0,0,0,0,0,0
26,False,NaN,12000000.0,"[Comedy, Drama, Family]",NaN,9263,tt0114011,Now and Then,Waxing nostalgic about the bittersweet passage...,8.68132,...,0,0,0,0,0,0,0,0,0,0
27,False,NaN,NaN,"[Drama, Romance]",NaN,17015,tt0114117,Persuasion,This film adaptation of Jane Austen's last nov...,2.22843,...,0,0,0,0,0,0,0,0,0,0
28,False,NaN,18000000.0,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,9.82242,...,0,0,0,0,0,0,0,0,0,0
29,False,NaN,NaN,"[Drama, Crime]",NaN,37557,tt0115012,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,1.10091,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46599,False,NaN,NaN,"[Action, Mystery, Thriller, Horror]",NaN,45527,tt1331329,The Final Storm,A stranger named Silas flees from a devastatin...,1.270832,...,0,0,0,0,0,0,0,0,0,0
46600,False,NaN,NaN,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,In a Heartbeat,A closeted boy runs the risk of being outed by...,20.82178,...,0,0,0,0,0,0,0,0,0,0
46601,False,NaN,NaN,[Drama],NaN,327237,tt3814486,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",0.590087,...,0,0,0,0,0,0,0,0,0,0
46602,False,NaN,NaN,"[Drama, Fantasy, Horror]",NaN,84710,tt0036975,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,0.143223,...,0,0,0,0,0,0,0,0,0,0
46603,False,NaN,NaN,"[Drama, Family, TV Movie]",NaN,39562,tt0889600,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",0.767762,...,0,0,0,0,0,0,0,0,0,0
46604,False,NaN,NaN,[Comedy],NaN,14008,tt0294425,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,4.392389,...,0,0,0,0,0,0,0,0,0,0
46605,False,NaN,NaN,[],NaN,44330,tt0135690,Le tripot clandestin,A combination gambling den and bawdy house is ...,0.21926,...,0,0,0,0,0,0,0,0,0,0
46606,False,NaN,NaN,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,1.618458,...,0,0,0,0,0,0,0,0,0,0
46607,False,NaN,NaN,[Fantasy],NaN,44333,tt0135179,Les cartes vivantes,A bearded magician holds up a large playing ca...,0.208349,...,0,0,0,0,0,0,0,0,0,0
46608,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49277,tt0135122,Les affiches en goguette,A wall full of advertising posters comes to life.,0.148131,...,0,0,0,0,0,0,0,0,0,0
46609,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49271,tt0127948,Le locataire diabolique,A man rents an apartment and furnishes it in r...,0.725084,...,0,0,0,0,0,0,0,0,0,0
46610,False,NaN,NaN,[],NaN,44324,tt0135631,Le Roi du maquillage,The background of this picture represents a sc...,0.213973,...,0,0,0,0,0,0,0,0,0,0
46611,False,NaN,NaN,[],NaN,122036,tt0224286,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,0.071782,...,0,0,0,0,0,0,0,0,0,0
46612,False,NaN,NaN,"[Animation, Family]",NaN,14885,tt0457437,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",2.568495,...,0,0,0,0,0,0,0,0,0,0
46613,False,NaN,NaN,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,...,0,0,0,0,0,0,0,0,0,0
46614,False,NaN,NaN,"[Comedy, Fantasy]",NaN,106807,tt0135571,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,0.225432,...,0,0,0,0,0,0,0,0,0,0
46615,False,NaN,NaN,[Documentary],NaN,276895,tt3054038,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",0.011025,...,0,0,0,0,0,0,0,0,0,0
46616,False,NaN,NaN,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,Maa,The bliss of a biology teacher’s family life i...,1.559596,...,0,0,0,0,0,0,0,0,0,0
46617,False,NaN,NaN,"[Comedy, Drama]",NaN,420346,tt4130180,The Morning After,The Morning After is a feature film that consi...,0.139936,...,0,0,0,0,0,0,0,0,0,0
46618,False,NaN,NaN,[],NaN,67179,tt0069215,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,0.225051,...,0,0,0,0,0,0,0,0,0,0
46619,False,NaN,NaN,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,House of Horrors,An unsuccessful sculptor saves a madman named ...,0.222814,...,0,0,0,0,0,0,0,0,0,0
46620,False,NaN,NaN,"[Mystery, Horror]",NaN,390959,tt0265736,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",0.076061,...,0,0,0,0,0,0,0,0,0,0
46621,False,NaN,NaN,[Horror],NaN,289923,tt0252966,The Burkittsville 7,A film archivist revisits the story of Rustin ...,0.38645,...,0,0,0,0,0,0,0,0,0,0
46622,False,NaN,NaN,[Science Fiction],NaN,222848,tt0112613,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,0.661558,...,0,0,0,0,0,0,0,0,0,0
46623,False,NaN,NaN,"[Drama, Action, Romance]",NaN,30840,tt0102797,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,...,0,0,0,0,0,0,0,0,0,0
46624,False,NaN,NaN,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,رگ خواب,Rising and falling between a man and woman.,0.072051,...,0,0,0,0,0,0,0,0,0,0
46625,False,NaN,NaN,[Drama],NaN,111109,tt2028550,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,...,0,0,0,0,0,0,0,0,0,0
46626,False,NaN,NaN,"[Action, Drama, Thriller]",NaN,67758,tt0303758,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,...,0,0,0,0,0,0,0,0,0,0
46627,False,NaN,NaN,[],NaN,227506,tt0008536,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,...,0,0,0,0,0,0,0,0,0,0
46628,False,NaN,NaN,[],NaN,461257,tt6980792,Queerama,50 years after decriminalisation of homosexual...,0.163015,...,0,0,0,0,0,0,0,0,0,0

In [299]:
# Find top 50 production companies who appear most frequently
counter = Counter([item for sublist in df['production_companies'].values for item in sublist])
top_production_companies = counter.most_common(50)

In [300]:
# For each movie, check whether a top-50 actor appeared
for name, count in top_production_companies:
    print(name)
    
    for index, row in df.iterrows():
        list_of_names = row['genres']
    
        if name in list_of_names:
            df['production_companies'+name] = 1
        else:
            df['production_companies'+name] = 0

Warner Bros.
Metro-Goldwyn-Mayer (MGM)
Paramount Pictures
Twentieth Century Fox Film Corporation
Universal Pictures
Canal+
Columbia Pictures Corporation
Columbia Pictures
RKO Radio Pictures
United Artists
New Line Cinema
Walt Disney Pictures
Touchstone Pictures
TriStar Pictures
Mosfilm
Miramax Films
France 2 Cinéma
Centre National de la Cinématographie (CNC)
Toho Company
BBC Films
Gaumont
StudioCanal
British Broadcasting Corporation (BBC)
Relativity Media
TF1 Films Production
Walt Disney Productions
Orion Pictures
Village Roadshow Pictures
Regency Enterprises
Lionsgate
Universal International Pictures (UI)
Zweites Deutsches Fernsehen (ZDF)
Dimension Films
DreamWorks SKG
Hammer Film Productions
Wild Bunch
Fox Searchlight Pictures
Rai Cinema
American International Pictures (AIP)
Film i Väst
Working Title Films
Svensk Filmindustri (SF)
Nordisk Film
Hollywood Pictures
Channel Four Films
Shaw Brothers
CJ Entertainment
Lions Gate Films
The Rank Organisation
Film4

In [301]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_title,overview,popularity,...,production_companiesWorking Title Films,production_companiesSvensk Filmindustri (SF),production_companiesNordisk Film,production_companiesHollywood Pictures,production_companiesChannel Four Films,production_companiesShaw Brothers,production_companiesCJ Entertainment,production_companiesLions Gate Films,production_companiesThe Rank Organisation,production_companiesFilm4
0,False,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,0,0,0,0,0,0,0,0,0,0
1,False,NaN,65000000.0,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,Jumanji,When siblings Judy and Peter discover an encha...,17.0155,...,0,0,0,0,0,0,0,0,0,0
2,False,Grumpy Old Men Collection,NaN,"[Romance, Comedy]",NaN,15602,tt0113228,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,0,0,0,0,0,0,0,0,0,0
3,False,NaN,16000000.0,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.85949,...,0,0,0,0,0,0,0,0,0,0
4,False,Father of the Bride Collection,NaN,[Comedy],NaN,11862,tt0113041,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.38752,...,0,0,0,0,0,0,0,0,0,0
5,False,NaN,60000000.0,"[Action, Crime, Drama, Thriller]",NaN,949,tt0113277,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.9249,...,0,0,0,0,0,0,0,0,0,0
6,False,NaN,58000000.0,"[Comedy, Romance]",NaN,11860,tt0114319,Sabrina,An ugly duckling having undergone a remarkable...,6.67728,...,0,0,0,0,0,0,0,0,0,0
7,False,NaN,NaN,"[Action, Adventure, Drama, Family]",NaN,45325,tt0112302,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.56116,...,0,0,0,0,0,0,0,0,0,0
8,False,NaN,35000000.0,"[Action, Adventure, Thriller]",NaN,9091,tt0114576,Sudden Death,International action superstar Jean Claude Van...,5.23158,...,0,0,0,0,0,0,0,0,0,0
9,False,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,GoldenEye,James Bond must unmask the mysterious head of ...,14.686,...,0,0,0,0,0,0,0,0,0,0
10,False,NaN,62000000.0,"[Comedy, Drama, Romance]",NaN,9087,tt0112346,The American President,"Widowed U.S. president Andrew Shepherd, one of...",6.31844,...,0,0,0,0,0,0,0,0,0,0
11,False,NaN,NaN,"[Comedy, Horror]",NaN,12110,tt0112896,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,5.43033,...,0,0,0,0,0,0,0,0,0,0
12,False,Balto Collection,NaN,"[Family, Animation, Adventure]",NaN,21032,tt0112453,Balto,An outcast half-wolf risks his life to prevent...,12.1407,...,0,0,0,0,0,0,0,0,0,0
13,False,NaN,44000000.0,"[History, Drama]",NaN,10858,tt0113987,Nixon,An all-star cast powers this epic look at Amer...,5.092,...,0,0,0,0,0,0,0,0,0,0
14,False,NaN,98000000.0,"[Action, Adventure]",NaN,1408,tt0112760,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",7.28448,...,0,0,0,0,0,0,0,0,0,0
15,False,NaN,52000000.0,"[Drama, Crime]",NaN,524,tt0112641,Casino,The life of the gambling paradise – Las Vegas ...,10.1374,...,0,0,0,0,0,0,0,0,0,0
16,False,NaN,16500000.0,"[Drama, Romance]",NaN,4584,tt0114388,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",10.6732,...,0,0,0,0,0,0,0,0,0,0
17,False,NaN,4000000.0,"[Crime, Comedy]",NaN,5,tt0113101,Four Rooms,It's Ted the Bellhop's first night on the job....,9.02659,...,0,0,0,0,0,0,0,0,0,0
18,False,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",NaN,9273,tt0112281,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",8.20545,...,0,0,0,0,0,0,0,0,0,0
19,False,NaN,60000000.0,"[Action, Comedy, Crime]",NaN,11517,tt0113845,Money Train,A vengeful New York transit cop decides to ste...,7.33791,...,0,0,0,0,0,0,0,0,0,0
20,False,Chili Palmer Collection,30250000.0,"[Comedy, Thriller, Crime]",NaN,8012,tt0113161,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,12.6696,...,0,0,0,0,0,0,0,0,0,0
21,False,NaN,NaN,"[Drama, Thriller]",NaN,1710,tt0112722,Copycat,An agoraphobic psychologist and a female detec...,10.7018,...,0,0,0,0,0,0,0,0,0,0
22,False,NaN,50000000.0,"[Action, Adventure, Crime, Thriller]",NaN,9691,tt0112401,Assassins,Assassin Robert Rath arrives at a funeral to k...,11.0659,...,0,0,0,0,0,0,0,0,0,0
23,False,NaN,NaN,"[Drama, Fantasy, Science Fiction, Thriller]",NaN,12665,tt0114168,Powder,Harassed by classmates who won't accept his sh...,12.1331,...,0,0,0,0,0,0,0,0,0,0
24,False,NaN,3600000.0,"[Drama, Romance]",http://www.mgm.com/title_title.do?title_star=L...,451,tt0113627,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",10.332,...,0,0,0,0,0,0,0,0,0,0
25,False,NaN,NaN,[Drama],NaN,16420,tt0114057,Othello,The evil Iago pretends to be friend of Othello...,1.8459,...,0,0,0,0,0,0,0,0,0,0
26,False,NaN,12000000.0,"[Comedy, Drama, Family]",NaN,9263,tt0114011,Now and Then,Waxing nostalgic about the bittersweet passage...,8.68132,...,0,0,0,0,0,0,0,0,0,0
27,False,NaN,NaN,"[Drama, Romance]",NaN,17015,tt0114117,Persuasion,This film adaptation of Jane Austen's last nov...,2.22843,...,0,0,0,0,0,0,0,0,0,0
28,False,NaN,18000000.0,"[Fantasy, Science Fiction, Adventure]",NaN,902,tt0112682,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,9.82242,...,0,0,0,0,0,0,0,0,0,0
29,False,NaN,NaN,"[Drama, Crime]",NaN,37557,tt0115012,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,1.10091,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46599,False,NaN,NaN,"[Action, Mystery, Thriller, Horror]",NaN,45527,tt1331329,The Final Storm,A stranger named Silas flees from a devastatin...,1.270832,...,0,0,0,0,0,0,0,0,0,0
46600,False,NaN,NaN,"[Family, Animation, Romance, Comedy]",NaN,455661,tt6969946,In a Heartbeat,A closeted boy runs the risk of being outed by...,20.82178,...,0,0,0,0,0,0,0,0,0,0
46601,False,NaN,NaN,[Drama],NaN,327237,tt3814486,"Bloed, Zweet en Tranen","Bloed, Zweet en Tranen (Blood, Sweat and Tears...",0.590087,...,0,0,0,0,0,0,0,0,0,0
46602,False,NaN,NaN,"[Drama, Fantasy, Horror]",NaN,84710,tt0036975,Jungle Woman,Paula the ape woman (Acquanetta) is alive and ...,0.143223,...,0,0,0,0,0,0,0,0,0,0
46603,False,NaN,NaN,"[Drama, Family, TV Movie]",NaN,39562,tt0889600,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",0.767762,...,0,0,0,0,0,0,0,0,0,0
46604,False,NaN,NaN,[Comedy],NaN,14008,tt0294425,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,4.392389,...,0,0,0,0,0,0,0,0,0,0
46605,False,NaN,NaN,[],NaN,44330,tt0135690,Le tripot clandestin,A combination gambling den and bawdy house is ...,0.21926,...,0,0,0,0,0,0,0,0,0,0
46606,False,NaN,NaN,"[Comedy, Fantasy, Science Fiction]",NaN,49279,tt0000359,L'Homme à la tête de caoutchouc,A chemist in his laboratory places upon a tabl...,1.618458,...,0,0,0,0,0,0,0,0,0,0
46607,False,NaN,NaN,[Fantasy],NaN,44333,tt0135179,Les cartes vivantes,A bearded magician holds up a large playing ca...,0.208349,...,0,0,0,0,0,0,0,0,0,0
46608,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49277,tt0135122,Les affiches en goguette,A wall full of advertising posters comes to life.,0.148131,...,0,0,0,0,0,0,0,0,0,0
46609,False,NaN,NaN,"[Fantasy, Comedy]",NaN,49271,tt0127948,Le locataire diabolique,A man rents an apartment and furnishes it in r...,0.725084,...,0,0,0,0,0,0,0,0,0,0
46610,False,NaN,NaN,[],NaN,44324,tt0135631,Le Roi du maquillage,The background of this picture represents a sc...,0.213973,...,0,0,0,0,0,0,0,0,0,0
46611,False,NaN,NaN,[],NaN,122036,tt0224286,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,0.071782,...,0,0,0,0,0,0,0,0,0,0
46612,False,NaN,NaN,"[Animation, Family]",NaN,14885,tt0457437,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",2.568495,...,0,0,0,0,0,0,0,0,0,0
46613,False,NaN,NaN,"[Fantasy, Action, Thriller]",NaN,49280,tt0135453,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,...,0,0,0,0,0,0,0,0,0,0
46614,False,NaN,NaN,"[Comedy, Fantasy]",NaN,106807,tt0135571,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,0.225432,...,0,0,0,0,0,0,0,0,0,0
46615,False,NaN,NaN,[Documentary],NaN,276895,tt3054038,Deep Hearts,"Deep Hearts is a film about the Bororo Fulani,...",0.011025,...,0,0,0,0,0,0,0,0,0,0
46616,False,NaN,NaN,"[Crime, Drama, Thriller]",NaN,404604,tt5690142,Maa,The bliss of a biology teacher’s family life i...,1.559596,...,0,0,0,0,0,0,0,0,0,0
46617,False,NaN,NaN,"[Comedy, Drama]",NaN,420346,tt4130180,The Morning After,The Morning After is a feature film that consi...,0.139936,...,0,0,0,0,0,0,0,0,0,0
46618,False,NaN,NaN,[],NaN,67179,tt0069215,San Michele aveva un gallo,Sentenced to life imprisonment for illegal act...,0.225051,...,0,0,0,0,0,0,0,0,0,0
46619,False,NaN,NaN,"[Horror, Mystery, Thriller]",NaN,84419,tt0038621,House of Horrors,An unsuccessful sculptor saves a madman named ...,0.222814,...,0,0,0,0,0,0,0,0,0,0
46620,False,NaN,NaN,"[Mystery, Horror]",NaN,390959,tt0265736,Shadow of the Blair Witch,"In this true-crime documentary, we delve into ...",0.076061,...,0,0,0,0,0,0,0,0,0,0
46621,False,NaN,NaN,[Horror],NaN,289923,tt0252966,The Burkittsville 7,A film archivist revisits the story of Rustin ...,0.38645,...,0,0,0,0,0,0,0,0,0,0
46622,False,NaN,NaN,[Science Fiction],NaN,222848,tt0112613,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,0.661558,...,0,0,0,0,0,0,0,0,0,0
46623,False,NaN,NaN,"[Drama, Action, Romance]",NaN,30840,tt0102797,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,...,0,0,0,0,0,0,0,0,0,0
46624,False,NaN,NaN,"[Drama, Family]",http://www.imdb.com/title/tt6209470/,439050,tt6209470,رگ خواب,Rising and falling between a man and woman.,0.072051,...,0,0,0,0,0,0,0,0,0,0
46625,False,NaN,NaN,[Drama],NaN,111109,tt2028550,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,...,0,0,0,0,0,0,0,0,0,0
46626,False,NaN,NaN,"[Action, Drama, Thriller]",NaN,67758,tt0303758,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,...,0,0,0,0,0,0,0,0,0,0
46627,False,NaN,NaN,[],NaN,227506,tt0008536,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,...,0,0,0,0,0,0,0,0,0,0
46628,False,NaN,NaN,[],NaN,461257,tt6980792,Queerama,50 years after decriminalisation of homosexual...,0.163015,...,0,0,0,0,0,0,0,0,0,0

In [302]:
df.shape

(46624, 17910)

In [ ]:
df.to_csv("Data/movies_Finaldata.csv.gz",index=False,compression="gzip")